# M√≥dulo 1

## Introdu√ß√£o

Etapas da transforma√ß√£o

![Transforma√ß√£o do JS para C++]("./images/modulo-1/JS-to-C++.png")

Todas as opera√ß√µes bloqueantes (acesso a BD, leitura de arquivos...) s√£o delegadas ao sistema operacional por meio do Event Loop. Quando a opera√ß√£o √© finalizada o sistema operacional envia um Callback (sinalizando que terminou) para o Event Loop que devolve para quem chamou.

Isso gera um problema de sincroniza√ß√£o.

> A forma com que seu c√≥digo √© escrito √© diferente da ordem em que √© executado.

Portanto, √© necess√°rio garantir a ordem de execu√ß√£o para evitar problemas (retornos indesejados).

![Event Loop]("./images/modulo-1/event-loop.png")

Para manipula√ß√£o do Event Loop (delega√ß√£o de eventos) √© utilizada somente uma Thread (SingleThread), mas quem trabalha com as Threads √© o pr√≥prio SO (Sistema Operacional).

## Estudo dos Callbacks

```
/*
 1 Obter um usuario
 2 Obter o numero de telefone de um usuario a partir de seu Id
 3 Obter o endereco do usuario pelo Id
*/

function getUser() {
  setTimeout(function () {
    return {
      id: 1,
      name: "Aladin",
      birthDate: new Date(),
    };
  }, 1000);
}

function getPhoneNumber(userId) {
  setTimeout(function () {
    return {
      phoneNumber: "1199002",
      ddd: 11,
    };
  }, 2000);
}

function getAddress(userId, callback) {
  setTimeout(function () {
    return {
      streetName: "dos bobos",
      number: 0,
    };
  }, 2000);
}

const user = getUser();
const phoneNumber = getPhoneNumber(user.id);

// Nesse caso usu√°rio ir√° retornar undefined
console.log(`Usu√°rio: ${user}`); // console.log("Usu√°rio", user);
console.log(`Telefone: ${phoneNumber}`); // console.log("Telefone", phoneNumber);
```

Retorno:
![Usu√°rio undefined]("./images/modulo-1/user-undefined.png")

Para resolver esse problema pode-se utilizar o Callback.

```
function getUser(callback) {
  setTimeout(function () {
    return callback(null, {
      id: 1,
      name: "Aladin",
      birthDate: new Date(),
    });
  }, 1000);
}

function resolveUser(error, user) {
  console.log(`Usu√°rio: ${user}`);
}

getUser(resolveUser);
```

Cria-se uma segunda fun√ß√£o (que ser√° o Callback) e essa fun√ß√£o √© passada para a fun√ß√£o getUser, para ser executada quando finalizado.

![Uso de Callback para retornar usu√°rio]("./images/modulo-1/user-callback.png")

```
function getUser(callback) {
  setTimeout(function () {
    return callback(null, {
      id: 1,
      name: "Aladin",
      birthDate: new Date(),
    });
  }, 1000);
}

function getPhoneNumber(userId, callback) {
  setTimeout(function () {
    return callback(null, {
      phoneNumber: "1199002",
      ddd: 11,
    });
  }, 2000);
}

getUser(function resolveUser(error, user) {
  if (error) {
    console.error("DEU RUIM EM USU√ÅRIO", error);
    return;
  }

  getPhoneNumber(user.id, function resolvePhoneNumber(error1, phoneNumber) {
    if (error1) {
      console.error("DEU RUIM EM TELEFONE", error);
      return;
    }
  });
});
```

A fun√ß√£o resolveUser que se comporta como a fun√ß√£o Callback √© passada para getUser, se retornar erro printa o erro e segue, sen√£o chama a fun√ß√£o getPhoneNumber, passa o id do usu√°rio e tamb√©m passa o Callback que √© esperado pela fun√ß√£o getPhoneNumber.

√â poss√≠vel notar que o callback √© sempre passado como √∫ltimo par√¢metro.

![Uso de Callback para retornar n√∫mero de telefone]("./images/modulo-1/phone-number-callback.png")

Por fim, faz-se o mesmo com endere√ßo.

![Uso de Callback para retornar endere√ßo]("./images/modulo-1/address-callback.png")

Depois de todos os Callbacks constru√≠dos e aninhados, √© poss√≠vel visualizar todos os dados.

![Informa√ß√µes do usu√°rio]("./images/modulo-1/all-informations-printed.png")

Por√©m, isso traz um problema. A quantidade de aninhamentos, mesmo que somente com 3 fun√ß√µes, j√° se torna dif√≠cil de manter e debuggar.

Os Callbacks resolvem o problema de sincronia, por√©m dificultam organiza√ß√£o, manuten√ß√£o e debugga√ß√£o do c√≥digo.

## Introdu√ß√£o a Promises

### Ciclo de vida

- üïô Pending: Estado inicial, ainda n√£o terminou ou ainda n√£o foi rejeitado.
- üéâ Fulfilled: Quando executou todas as opera√ß√µes com sucesso.
- ‚ùå Rejected: Quando a opera√ß√£o falhou.

Ao refatorar o c√≥digo de Callback para Promise, temos o seguinte:

```
function getUser() {
  return new Promise(function resolvePromise(resolve, reject) {
    setTimeout(function () {
      return resolve({
        id: 1,
        name: "Aladin",
        birthDate: new Date(),
      });
    }, 1000);
  });
}

const userPromise = getUser();

userPromise
  .then(function (result) {
    console.log("resultado", result);
  })
  .catch(function (error) {
    console.error("DEU RUIM", error);
  });

```

![Refatora√ß√£o do Callback de Usu√°rio para Promise]("./images/modulo-1/user-promise.png")

O objeto Promise √© instanciado e nele √© passado uma fun√ß√£o que ir√° retornar duas fun√ß√µes: a fun√ß√£o respons√°vel por lidar com o resultado e a fun√ß√£o respons√°vel por lidar com o erro. Nisso, h√° uma separa√ß√£o de responsabilidades. Para capturar o resultado utiliza-se **then** e para capturar o erro **catch**. √â poss√≠vel tamb√©m lidar com o erro pelo **then**, como exemplo abaixo:

```
userPromise
    .then(function(result) {
        //do something...
    }, function (error) {
        //do something...
    })
```

Se na fun√ß√£o for retornado o reject, o erro √© mostrado pois √© capturado pelo catch:

```
function getUser() {
  return new Promise(function resolvePromise(resolve, reject) {
    setTimeout(function () {
      return reject(new Error("DEU RUIM DE VERDADE!"));

      return resolve({
        id: 1,
        name: "Aladin",
        birthDate: new Date(),
      });
    }, 1000);
  });
}
```

![Retorno de erro na Promise de Usu√°rio]("./images/modulo-1/user-promise-error.png")

Refatorando tudo para utilizar somente Promises:

```
function getUser() {
  return new Promise(function resolvePromise(resolve, reject) {
    setTimeout(function () {
      // return reject(new Error("DEU RUIM DE VERDADE!"));

      return resolve({
        id: 1,
        name: "Aladin",
        birthDate: new Date(),
      });
    }, 1000);
  });
}

function getPhoneNumber(userId) {
  return new Promise(function resolvePromise(resolve, reject) {
    setTimeout(function () {
      return resolve({
        phoneNumber: "1199002",
        ddd: 11,
      });
    }, 2000);
  });
}

function getAddress(userId) {
  return new Promise(function resolvePromise(resolve, reject) {
    setTimeout(function () {
      return resolve({
        streetName: "dos bobos",
        number: 0,
      });
    }, 2000);
  });
}

const userPromise = getUser();

//CONCEITO DE PIPE:
// usuario -> telefone -> endere√ßo
userPromise
  .then(function (user) {
    return getPhoneNumber(user.id).then(function (phoneNumber) {
      return getAddress(user.id).then(function (address) {
        return {
          user: {
            id: user.id,
            name: user.name,
          },
          phoneNumber: `(${phoneNumber.ddd})${phoneNumber.phoneNumber}`,
          address: `${address.streetName}, ${address.number}`,
        };
      });
    });
  })
  .then(function (result) {
    console.log("Resultado", result);
  })
  .catch(function (error) {
    console.error("DEU RUIM", error);
  });
```

![Resultado com Promises]("./images/modulo-1/all-promises.png")

O pr√≥prio Node.js possui um m√≥dulo interno que auxilia na transforma√ß√£o de Callback para Promise, sem que precisemos instanciar em toda fun√ß√£o.

```
const util = require("util");

const getAddressAsync = util.promisify(getAddress);
const getUserAsync = util.promisify(getUser);
const getPhoneNumberAsync = util.promisify(getPhoneNumber);

function getUser(callback) {
  setTimeout(function () {
    return callback(null, {
      id: 1,
      name: "Aladin",
      birthDate: new Date(),
    });
  }, 1000);
}

...
```

Cada fun√ß√£o passada para promisify √© referente ao Callback como visto inicialmente. O resultado retornado √© uma Promise.

```
userPromise
  .then(function (user) {
    const phoneNumberPromise = getPhoneNumberAsync(user.id);
    return phoneNumberPromise.then(function (phoneNumber) {
      const addressPromise = getAddressAsync(user.id);
      return addressPromise.then(function (address) {
        return {
          user: {
            id: user.id,
            name: user.name,
          },
          phoneNumber: `(${phoneNumber.ddd})${phoneNumber.phoneNumber}`,
          address: `${address.streetName}, ${address.number}`,
        };
      });
    });
  })
  .then(function (result) {
    console.log("Resultado", result);
  })
  .catch(function (error) {
    console.error("DEU RUIM", error);
  });
```

Se o primeiro par√¢metro do Callback da fun√ß√£o que retorna o Callback, for diferente de nulo, ao inv√©s de printar o resultado, ele vai printar o erro.

```
function getUser(callback) {
  setTimeout(function () {
    return callback(345345345, {
      id: 1,
      name: "Aladin",
      birthDate: new Date(),
    });
  }, 1000);
}
```

Portanto, ao inv√©s de cair no then result, ir√° cair no catch error.

O Promisify s√≥ funciona corretamente se estiver sendo utilizado o Callback da forma esperada (convencional).

Mesmo assim, ainda √© dif√≠cil de gerenciar e manter, com muitos aninhamentos, tendo que sempre resolver uma promise para resolver outra.

## Introdu√ß√£o de Promises com async/await

```
main();
async function main() {
  try {
    const user = await getUserAsync();
    const phoneNumber = await getPhoneNumberAsync(user.id);
    const address = await getAddressAsync(user.id);

    console.log(`
        Nome: ${user.name}
        Telefone: (${phoneNumber.ddd})${phoneNumber.phoneNumber}
        Endere√ßo: ${address.streetName}, ${address.number}
      `);
  } catch (error) {
    console.error("DEU RUIM", error);
  }
}
```

A sintaxe async/await vem como um facilitador na hora de trabalhar com Promises, reduzindo c√≥digo e complexidade. Por√©m, uma chamada await pode interromper todo um fluxo, e √© nessas horas que necessita verificar quem depende de quem.

No c√≥digo acima, pode-ser ter uma melhoria no tempo de resposta utilizando a fun√ß√£o Promise.all.

```

main();
async function main() {
  try {
    const user = await getUserAsync();

    const [phoneNumber, address] = await Promise.all([
      getPhoneNumberAsync(user.id),
      getAddressAsync(user.id),
    ]);

    console.log(`
        Nome: ${user.name}
        Telefone: (${phoneNumber.ddd})${phoneNumber.phoneNumber}
        Endere√ßo: ${address.streetName}, ${address.number}
      `);
  } catch (error) {
    console.error("DEU RUIM", error);
  }
}

```

Como endere√ßo n√£o depende da resolu√ß√£o da Promise de telefone, √© poss√≠vel colocar ambas as fun√ß√µes na fila de Promises. Portanto, n√£o ter√° o tempo de espera a mais (somente da pr√≥pria Promise).

Diferen√ßa de tempo de resposta entre ambos os casos:

![Tempo de resposta maior com async/await]("./images/modulo-1/async-await-longer.png")

![Tempo de resposta menor com async/await]("./images/modulo-1/async-await-shorter.png")

## Manipula√ß√£o de eventos com EventEmitter

Tudo que ocorre e √© manipulado no JavaScript ocorre a partir de eventos, portanto ele √© Event Driven (Orientado a Eventos).

Trabalha sob o Design Pattern Observer/PubSub.

![Observer Design Pattern]("./images/modulo-1/observer.png")

Primeiro exemplo:

```

const EventEmitter = require("events");

class MyEmitter extends EventEmitter {}

const myEmitter = new MyEmitter();
const userClicked = "usuario:click";

myEmitter.on(userClicked, function (click) {
  console.log("um usuario clicou", click);
});

myEmitter.emit(userClicked, "na barra de rolagem");
myEmitter.emit(userClicked, "no ok");

let count = 0;
setInterval(function () {
  myEmitter.emit(userClicked, "no ok" + count++);
}, 1000);

```

Segundo exemplo:

```
const stdin = process.openStdin();

stdin.addListener("data", function (value) {
    console.log(`Voc√™ digitou: ${value.toString().trim()}`);
    return resolve(value);
});

```

Enquanto receber eventos, ser√° executado, diferente da Promise que executa uma vez.

```
const stdin = process.openStdin();

function main() {
  return new Promise(function (resolve, reject) {
    stdin.addListener("data", function (value) {
      return resolve(value);
    });
  });
}

main().then(function (result) {
  console.log("resultado", result.toString());
});
```

Mesmo que exista um Listener, por ser uma Promise, ser√° executado somente uma vez.
